version: "3.8"

services:
  web:
    container_name: service-pedido
    build:
      context: .
    volumes:
      - ".:/app"
      - "/node_modules"
    ports:
      - 3001:3000
    environment:
      DEBUG : ${DEBUG}
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_URL : ${AWS_SQS_URL}
      AWS_SQS_PEDIDO_ENTREGA : ${AWS_SQS_PEDIDO_ENTREGA}
      MONGO_PASS: service-pedido
      MONGO_PORT: 27017
      MONGO_COLLECTION: admin
      CHOKIDAR_USEPOLLING: "true"
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASS: ${MARIADB_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PORT: ${MARIADB_PORT}
    depends_on:
      - maria-db-pedido
    networks:
        - microservice-fiap

  maria-db-pedido:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASS}
    ports:
      - 3309:3306
    networks:
      - microservice-fiap

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Porta para acesso ao SQS
    environment:
      - SERVICES=sqs,iam
      - DEFAULT_REGION=us-east-1
    networks:
      - microservice-fiap


volumes:
  mariadb-data:

networks:
  microservice-fiap:
    external: true
